api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
    defaults:
        pagination_client_items_per_page: true
    collection:
        pagination:
            # items_per_page_parameter_name: "%env(itp)%"
            items_per_page_parameter_name: itemsPerPage
    formats:
        jsonld:
            mime_types:
                - application/ld+json
        json:
            mime_types:
                - application/json
        html:
            mime_types:
                - text/html
        jsonhal:
            mime_types:
                - application/hal+json
        csv:
            mime_types:
                - application/csv

